headlamp:
  config:
    inCluster: true
    extraArgs:
      - -oidc-use-access-token
    oidc:
      secret:
        create: false
      externalSecret:
        enabled: true
        name: headlamp-oidc
